@{
    ExcludeRules=@('PSDSCDscExamplesPresent',
                'PSDSCDscTestsPresent',
                'PSUseBOMForUnicodeEncodedFile',
                'PSUseShouldProcessForStateChangingFunctions',
                'PSUseSingularNouns',
                'PSUseToExportFieldsInManifest',
                'PSUseUTF8EncodingForHelpFile',
                'PSUseDeclaredVarsMoreThanAssignments')
}
