
[ClassVersion("1.0.0.1"), FriendlyName("WinEventLog")]
class MSFT_WinEventLog : OMI_BaseResource
{
    [Key, Description("Name of the event log")] String LogName;
    [Write, Description("sizethat the event log file is allowed to be When the file reaches this maximum size it is considered full")] Sint64 MaximumSizeInBytes;
    [Write] Boolean IsEnabled;
    [Write, ValueMap{"AutoBackup","Circular","Retain"}, Values{"AutoBackup","Circular","Retain"}] String LogMode;
    [Write] String SecurityDescriptor;
    [Write] String LogFilePath;
    [Write] Sint32 LogRetentionDays;
};
