
[ClassVersion("1.0.0.0"), FriendlyName("xVirtualMemory")]
class MSFT_xVirtualMemory : OMI_BaseResource
{
    [Key] String Drive;
    [Key, ValueMap{"AutoManagePagingFile","CustomSize","SystemManagedSize","NoPagingFile"}, Values{"AutoManagePagingFile","CustomSize","SystemManagedSize","NoPagingFile"}] String Type;
    [Write] Sint64 InitialSize;
    [Write] Sint64 MaximumSize;
};

