# Culture = "en-US"
ConvertFrom-StringData -StringData @'
    SystemProtectionState            = Overall system protection state is '{0}'. (SP0001)
    UnknownOperatingSystemError      = The operating system threw an error trying to retrieve system protection settings. (SP0002)
    GetEnabledDrivesFailure          = An error occurred trying to retrieve the list of drives where system protection is enabled. (SP0003)
    ProtectedDrivesAddition          = Added drive '{0}' to list of protected drives with maximum disk usage of '{1}' bytes. (SP0004)
    DriveFound                       = Drive '{0}' has system protection enabled with maximum disk usage of '{1}' bytes. (SP0005)
    DriveSkipped                     = Skipping drive '{0}' because it is not the drive to test (SP0006)
    InDesiredStateDriveLetter        = Set inDesiredState to '{0}' based on drive letter evaluation. (SP0007)
    MultipleSettings                 = Cannot process configuration with DriveLetter and Frequency in the same resource declaration. (SP0008)
    InsufficentArguments             = You must specify either DriveLetter or Frequency. (SP0009)
    EnableRestoreFailure             = An unexpected error occurred trying to enable system protection on drive '{0}'. (SP0010)
    DisableRestoreFailure            = An unexpected error occurred trying to disable system protection on drive '{0}'. (SP0011)
    InDesiredStateDiskUsageFalse     = Set inDesiredState to false because the current maximum disk usage for drive '{0}' is not in the desired state. (SP0012)
    InDesiredStateDiskUsageUnchanged = Not changing inDesiredState because the current maximum disk usage for drive '{0}' is in the desired state. (SP0013)
    EnableComputerRestore            = System protection for drive '{0}' has been enabled successfully. (SP0014)
    DisableComputerRestore           = System protection for drive '{0}' has been disabled successfully. (SP0015)
    SetFrequency                     = System protection frequency has been set to '{0}'. (SP0016)
    SetFrequencyFailure              = An unexpected error occurred trying to configure the system protection frequency. (SP0017)
    VssShadowResizeFailure           = An unexpected error occurred trying to configure the maximum disk usage for drive '{0}'. (SP0018)
    VssShadowDeleteFailure           = An unexpected error occurred tying to delete restore points for drive '{0}'. VSS corruption and/or orphaned shadow copies are the most likely reasons for the failure. (SP0019)
    VssShadowResizeFailureWithForce  = Deleting restore points for drive '{0}' because the resize operation failed and the Force option was specified. (SP0020)
    VssShadowResizeFailureWithForce2 = An unexpected error occurred trying to configure the maximum disk usage for drive '{0}' even after deleting its restore points. VSS corruption and/or orphaned shadow copies are the most likely reasons for the failure. (SP0021)
'@
