# Culture = "en-US"
ConvertFrom-StringData -StringData @'
    NotWorkstationOS                 = This resource can only be used on workstation operating systems. (SP0001)
    FoundServerOS                    = It appears we are running on a server operating system (ProductType = {0}). (SP0002)
    FoundWorkstationOS               = It appears we are running on a worksstation operating system (ProductType = {0}). (SP0003)
    ReturningTrueToBeSafe            = The test will evaluate to True to prevent an unintentional set targeting a server operating system. (SP0004)
    SystemProtectionState            = Overall system protection state is {0}. (SP0005)
    UnknownOperatingSystemError      = The operating system threw an error trying to retrieve system protection settings. (SP0006)
    GetEnabledDrivesFailure          = An error occurred trying to retrieve the list of drives where system protection is enabled. (SP0007)
    DriveFound                       = Drive {0} has system protection enabled with maximum disk usage of {1} percent. (SP0008)
    DriveSkipped                     = Skipping drive {0} because it is not the drive to find (SP0009)
    VssAdminReturnValues             = {1} Operation: VSS returned exit code {0} (Force = {2}). (SP0010)
    InDesiredStateDriveLetter        = Set inDesiredState to {0} based on drive letter evaluation. (SP0011)
    EnableComputerRestoreFailure     = An unexpected error occurred trying to enable system protection on drive {0}. (SP0012)
    DisableComputerRestoreFailure    = An unexpected error occurred trying to disable system protection on drive {0}. (SP0013)
    InDesiredStateDiskUsageFalse     = Set inDesiredState to false because the current maximum disk usage for drive {0} is not in the desired state. (SP0014)
    InDesiredStateDiskUsageUnchanged = Not changing inDesiredState because the current maximum disk usage for drive {0} is in the desired state. (SP0015)
    EnableComputerRestoreSuccess     = System protection for drive {0} has been enabled successfully. (SP0016)
    DisableComputerRestoreSuccess    = System protection for drive {0} has been disabled successfully. (SP0017)
    VssShadowResizeSuccess           = System protection disk usage was changed successfully. (SP0018)
    VssShadowResizeFailure           = An unexpected error occurred trying to configure the maximum disk usage for drive {0}. (SP0019)
    VssShadowDeleteFailure           = An unexpected error occurred tying to delete restore points for drive {0}. VSS corruption and/or orphaned shadow copies are the most likely reasons for the failure. (SP0020)
    VssShadowResizeFailureWithForce  = Deleting restore points for drive {0} because the resize operation failed and the Force option was specified. (SP0021)
    VssShadowResizeFailureWithForce2 = An unexpected error occurred trying to configure the maximum disk usage for drive {0} even after deleting its restore points. VSS corruption and/or orphaned shadow copies are the most likely reasons for the failure. (SP0022)
'@
