
[ClassVersion("1.0.0.0"), FriendlyName("LanguagePack")]
class MSFT_LanguagePack : OMI_BaseResource
{
    [Key] String LanguagePackName;
    [Write] String LanguagePackLocation;
    [Write] Boolean SuppressReboot;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

